spring:
  application:
    name: xslt-service
  cloud:
    config:
      uri: http://localhost:9000
      enabled: true
      profile: remote
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: xslt-service
    redis:
      repositories:
        enabled:
          false      
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
server:
  port: 30080
  servlet:
    context-path: /xslt-service
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: false
    hostname: localhost
config:
   name: gh1
xml:
  validation: true  
